### ISSUE TITLE
Yii2's `camel2d()`

### ISSUE THREAD

**Issue by khalwat** [tilingue/craft-twig-matrix-match#1]
You could consider exposing Yii2's built-in `camel2id()` method:

https://www.yiiframework.com/doc/api/2.0/yii-helpers-baseinflector#camel2id()-detail

For example:

```php
use yii\helpers\Inflector;

$kebab = Inflector::camel2id($handle);
```

Untested, but:

```php
<?php

namespace squirreldev\twigmatrixmatch\extensions;

use Twig\Extension\AbstractExtension;

class CamelToHypenExtension extends AbstractExtension {

    /**
     * @return string
     */
    public function getName() {
        return Craft::t('twigmatrixmatch', 'String Extension');
    }

    public function getFilters() {
        return [
            new \Twig_SimpleFilter('camel2id', [Inflector::class, 'camel2id']);
        ];
    }
}
```

I _think_ it'll give you the same result.

**Comment by tilingue** [comment]
Thanks a lot for the suggestion. It worked perfectly!

You can find the fix in the release 1.1.0.

**Comment by khalwat** [comment]
Oh, there was nothing wrong with what you did -- just was pointing out maybe a simpler way to achieve the same result.

**Comment by tilingue** [comment]
> Oh, there was nothing wrong with what you did -- just was pointing out maybe a simpler way to achieve the same result.

@khalwat It is always good to learn from one who knows more actually :D I'm pretty new using Craft and any suggestion to improve what I'm doing is very welcome. Thanks again!
